# Porta padrão MQTT (TCP)
listener 1883 0.0.0.0
allow_anonymous true

# Porta para WebSockets (usada pelo painel web)
listener 9001 0.0.0.0
protocol websockets
allow_anonymous true

# Persistência
persistence true
persistence_location /mosquitto/data/

# Logs
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
